### ISSUE TITLE
No keybindings?

### ISSUE THREAD

**Issue by jfmcbrayer** [chenyanming/wallabag.el#2]
Hi! I've loaded wallabag.el using use-package, pretty much as you give in the instructions, except that I'm loading straight from github using quelpa-use-package.

I can get it to load my database from wallabag, but there don't seem to be any keybindings in wallabag-search-mode. I also can't find anything setting the keybindings in the source. Have they just been forgotten? Calling the corresponding functions with M-x all work as expected.

**Comment by chenyanming** [comment]
It is wired. I provided both evil and non-evil. Please check `wallabag-search-mode-map`.

**Comment by karthink** [comment]
`wallabag-search-mode-map` is populated, but it's not active in `wallabag-search-mode` for me.

Also, may I suggest the following changes to the defaults in the (non-evil) version of `wallabag-search-mode-map`?

```emacs-lisp
    (define-key map "g" #'wallabag-search-refresh-and-clear-filter) ;; r -> g
    (define-key map "G" #'wallabag-search-clear-filter)             ;; R -> G      
    (define-key map "n" #'wallabag-next-entry)                      ;; j -> n
    (define-key map "p" #'wallabag-previous-entry)                  ;; k -> p
    (define-key map "y" #'wallabag-org-link-copy)                   ;; y -> w
```

This is in keeping with all emacs packages that display lists of entries, like dired, gnus, notmuch, elfeed etc. Most Emacs users have years of muscle memory for navigation with `n`,`p` and refreshing with `g`.

**Comment by chenyanming** [comment]
Fix by af74af6fabc56bf4c8731feebceb1bbd630ca072. Add Proper non-evil keys just like suggestion. @karthink @jfmcbrayer

**Comment by chenyanming** [comment]
map was changed to cl-map 8da206cf5dee5b1e4ce4133d43ea6d917d76435c. @karthink

**Comment by jfmcbrayer** [comment]
I can verify that this is fixed.
