### ISSUE TITLE
Search by read/unread status; set read/unread status

### ISSUE THREAD

**Issue by jfmcbrayer** [chenyanming/wallabag.el#6]
I can't seem to find any functions dealing with the read/unread status of bookmarks. It would be good to be able to display only unread (or read) bookmarks, and to set or clear the read flag on bookmarks.

It looks like the relevant API is PATCH /api/entries/{entry}.{_format}

**Comment by chenyanming** [comment]
The uread/read/starred and advanced filter is on development.

**Comment by chenyanming** [comment]
I guess the new commit already finished this feature, please check 770c9db1c56eb6a9d7e66fc3188a04e37fa8c5b0.

**Comment by chenyanming** [comment]
You can get into `wallabag-sidebar-mode` and click the groups to filter the results.
<img width="1057" alt="Screen Shot 2021-04-17 at 8 02 02 PM" src="https://user-images.githubusercontent.com/3462132/115112384-da959600-9fb7-11eb-81d1-4ee8b6c87aaf.png">

**Comment by chenyanming** [comment]
Tag groups are not so actuate, it will improve in the future.
